"""Core ``explain()`` entry point: turn a fitted model into an LLM explanation."""

from __future__ import annotations

import copy
from typing import Any, Optional

from ._prompting import assemble_system_prompt, build_user_prompt, remove_fences
from .model_handlers import get_handler

_VALID_AUDIENCES = (
    "novice",
    "student",
    "researcher",
    "manager",
    "domain_expert",
)
_VALID_VERBOSITY = ("brief", "moderate", "detailed")
_VALID_STYLES = ("markdown", "html", "json", "text", "latex")


def _validate_choice(name: str, value: str, choices: tuple) -> str:
    if value not in choices:
        raise ValueError(f"`{name}` must be one of {choices!r}, got {value!r}.")
    return value


def _chat_once(client: Any, system_prompt: str, user_prompt: str) -> str:
    """Send a single system+user prompt turn without mutating the caller's
    ``chatlas.Chat`` object.

    ``chatlas.Chat`` has no ``clone()`` method; ``copy.deepcopy()`` is
    chatlas's own documented/tested pattern for forking a ``Chat`` (see
    ``Chat.to_solver()`` in chatlas's source, and
    ``tests/test_chat.py::test_deepcopy_chat``). This mirrors the R/ellmer
    implementation's ``client$clone()`` + ``set_turns(list())`` +
    ``set_system_prompt()`` pattern exactly.
    """
    temp_chat = copy.deepcopy(client)
    temp_chat.set_turns([])  # clear any existing history (system prompt aside)
    temp_chat.system_prompt = system_prompt
    response = temp_chat.chat(user_prompt, echo="none", stream=False)
    return str(response)


def explain(
    model_object: Any,
    client: Any,
    context: Optional[str] = None,
    language: Optional[str] = None,
    audience: str = "novice",
    verbosity: str = "moderate",
    style: str = "markdown",
    prompt_dir: Optional[str] = None,
) -> dict:
    """Explain a statistical model's output using an LLM.

    Supported Models
    ----------------
    This function supports fitted model objects from the following packages:
    * **statsmodels**:
      - ``OLS`` (Ordinary Least Squares regression)
      - ``GLM`` (Generalized Linear Models, e.g., Binomial, Gamma, NegBinomial)
      - ``MixedLM`` (Linear Mixed Effects models)
      - ``ARIMA`` / ``SARIMAX`` (Time Series models)
      - ``PHReg`` (Cox Proportional Hazards regression)
    * **lifelines** (optional):
      - ``CoxPHFitter`` (Cox Proportional Hazards survival models)
      - ``WeibullAFTFitter`` / ``LogNormalAFTFitter`` / ``LogLogisticAFTFitter``
        (Parametric Accelerated Failure Time survival models)
    * **pygam** (optional):
      - ``GAM`` / ``LinearGAM`` / ``LogisticGAM`` / ``PoissonGAM``
        (Generalized Additive Models)

    Parameters
    ----------
    model_object : Any
        A fitted statistical model object from a supported library (e.g., a
        results object from ``statsmodels``).
    client : chatlas.Chat
        A chatlas ``Chat`` client (e.g. from ``chatlas.ChatOpenAI()`` or
        ``chatlas.ChatAnthropic()``). Never mutated by this function.
    context : str, optional
        Additional context about the data or research question to provide
        to the LLM.
    language : str, optional
        The language the explanation should be written in (e.g. "Spanish",
        "French", "Mandarin Chinese"). If None (the default), no language
        constraint is added and the LLM will typically respond in the same
        language as the input/context or its default language.
    audience : str, optional
        The target audience: one of "novice" (default), "student",
        "researcher", "manager", or "domain_expert".
    verbosity : str, optional
        The desired level of detail: one of "brief", "moderate" (default),
        or "detailed".
    style : str, optional
        The output format style: one of "markdown" (default), "html",
        "json", "text", or "latex".
    prompt_dir : str, optional
        Custom prompts directory path to override package prompts.

    Returns
    -------
    dict
        A dictionary with keys: ``text``, ``model_type``, ``audience``,
        ``verbosity``, ``style``.
    """
    audience = _validate_choice("audience", audience, _VALID_AUDIENCES)
    verbosity = _validate_choice("verbosity", verbosity, _VALID_VERBOSITY)
    style = _validate_choice("style", style, _VALID_STYLES)

    handler = get_handler(model_object)
    model_name, engine, summary_text = handler(model_object)

    system_prompt = assemble_system_prompt(
        model_name, audience, verbosity, style, engine=engine, language=language, prompt_dir=prompt_dir
    )
    user_prompt = build_user_prompt(
        model_description=f"{model_name} model", output=summary_text, context=context
    )

    explanation_text = remove_fences(_chat_once(client, system_prompt, user_prompt)) or ""

    # Append deterministic caution/disclaimer
    disclaimer = (
        "\n\n***\n"
        "*Caution: This explanation was generated by a Large Language Model. Users should critically review the output and consult additional statistical resources or experts to ensure correctness and a full understanding.*"
    )
    explanation_text += disclaimer

    return {
        "text": explanation_text,
        "model_type": model_name,
        "audience": audience,
        "verbosity": verbosity,
        "style": style,
    }


def suggest_code(explanation: dict) -> str:
    """Suggest code snippets to run next based on a model explanation.

    Parameters
    ----------
    explanation : dict
        The dictionary returned by `explain()`.

    Returns
    -------
    str
        A formatted string of suggested Python diagnostics code.
    """
    model_type = explanation.get("model_type")

    if model_type == "linear_model":
        return (
            "# Next Steps: Suggested Python Coding Diagnostics\n\n"
            "# 1. Plot Residuals vs Fitted values\n"
            "import matplotlib.pyplot as plt\n"
            "import seaborn as sns\n"
            "import statsmodels.api as sm\n\n"
            "# Assuming 'model' is your fitted OLSResults object\n"
            "fig, ax = plt.subplots(figsize=(8, 5))\n"
            "sns.residplot(x=model.fittedvalues, y=model.resid, lowess=True,\n"
            "              scatter_kws={'alpha': 0.5},\n"
            "              line_kws={'color': 'red', 'lw': 1, 'alpha': 0.8}, ax=ax)\n"
            "ax.set_title('Residuals vs Fitted')\n"
            "ax.set_xlabel('Fitted values')\n"
            "ax.set_ylabel('Residuals')\n"
            "plt.show()\n\n"
            "# 2. Test for Homoscedasticity (Breusch-Pagan)\n"
            "from statsmodels.stats.diagnostic import het_breuschpagan\n"
            "bp_test = het_breuschpagan(model.resid, model.model.exog)\n"
            "labels = ['Lagrange multiplier statistic', 'p-value', 'f-value', 'f p-value']\n"
            "print(dict(zip(labels, bp_test)))\n\n"
            "# 3. Test for Autocorrelation (Durbin-Watson)\n"
            "from statsmodels.stats.stattools import durbin_watson\n"
            "dw = durbin_watson(model.resid)\n"
            "print(f'Durbin-Watson statistic: {dw}')\n\n"
            "# 4. Check Multicollinearity (VIF)\n"
            "from statsmodels.stats.outliers_influence import variance_inflation_factor\n"
            "for i in range(1, model.model.exog.shape[1]):\n"
            "    vif = variance_inflation_factor(model.model.exog, i)\n"
            "    print(f'VIF for predictor {i}: {vif}')\n\n"
            "***\n"
            "*Caution: These code suggestions were generated by a Large Language Model. Users should critically review the code to ensure correctness and applicability before executing.*"
        )
    elif model_type == "generalized_linear_model":
        return (
            "# Next Steps: Suggested Python Coding Diagnostics\n\n"
            "# 1. Plot Pearson Residuals vs Fitted values\n"
            "import matplotlib.pyplot as plt\n"
            "import seaborn as sns\n\n"
            "# Assuming 'model' is your fitted GLMResults object\n"
            "fig, ax = plt.subplots(figsize=(8, 5))\n"
            "sns.residplot(x=model.fittedvalues, y=model.resid_pearson, lowess=True,\n"
            "              scatter_kws={'alpha': 0.5},\n"
            "              line_kws={'color': 'red', 'lw': 1, 'alpha': 0.8}, ax=ax)\n"
            "ax.set_title('Pearson Residuals vs Fitted')\n"
            "ax.set_xlabel('Fitted values')\n"
            "ax.set_ylabel('Pearson Residuals')\n"
            "plt.show()\n\n"
            "# 2. Check for Overdispersion\n"
            "pearson_chi2 = model.pearson_chi2\n"
            "df_resid = model.df_resid\n"
            "dispersion = pearson_chi2 / df_resid\n"
            "print(f'Dispersion parameter: {dispersion}')\n\n"
            "***\n"
            "*Caution: These code suggestions were generated by a Large Language Model. Users should critically review the code to ensure correctness and applicability before executing.*"
        )
    else:
        return (
            "# Next Steps: Suggested Python Coding Diagnostics\n\n"
            "# 1. Print model summary\n"
            "print(model.summary())\n\n"
            "# 2. Plot diagnostics if supported\n"
            "# (Check library documentation for specific diagnostic plots)\n\n"
            "***\n"
            "*Caution: These code suggestions were generated by a Large Language Model. Users should critically review the code to ensure correctness and applicability before executing.*"
        )
